apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
  namespace: bazook
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  acme:
    email: rcnoetic@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: rcnoetic@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-secret
            key: api-key
