apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-certificates
  namespace: bazook
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  secretName: app-certificates
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'rkth.io'
